[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
enableWebsocketCompression = false
maxMessageSize = 200

[theme]
primaryColor = "#3498db"
backgroundColor = "#0f1419"
secondaryBackgroundColor = "#1a1f24"
textColor = "#fafafa"

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false

[runner]
fastReruns = true
magicEnabled = true

[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"
