[server]
port = 8533
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
address = "localhost"

[theme]
primaryColor = "#007AFF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
serverAddress = "localhost"
gatherUsageStats = false
