[streamlit]
deploymentMode = "cloud"

[server]
runOnSave = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#3498db"
backgroundColor = "#0f1419"
secondaryBackgroundColor = "#1a1f24"
textColor = "#fafafa"
